In [1]:
import numpy as np

###  1. Create a null vector of size 10 but the fifth value which is 1.

In [4]:
z = np.zeros(10)

In [6]:
z[4] = 1

In [7]:
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

###  2. Create a vector with values ranging from 10 to 49.

In [10]:
x = np.arange(10,50)

In [11]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
y = np.arange(0,9).reshape(3,3)

In [14]:
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [19]:
a = [1,2,0,0,4,0]

In [25]:
def non_zero(lst):
    n_z = []
    n_z_i = []
    for i in range(len(lst)):
        if lst[i] != 0:
            n_z.append(lst[i])
            n_z_i.append(i)
    print('The non zero elements from given input is : ',n_z)
    print('the non zero element index from given input is : ',n_z_i)
    return n_z, n_z_i

In [26]:
b,c = non_zero(a)

The non zero elements from given input is :  [1, 2, 4]
the non zero element index from given input is :  [0, 1, 4]


In [28]:
print(b)
print(c)

[1, 2, 4]
[0, 1, 4]


### 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [29]:
p = np.random.rand(10,10)

In [30]:
p

array([[0.92316029, 0.88585658, 0.61323361, 0.52101454, 0.92238624,
        0.42074928, 0.49910864, 0.39586712, 0.80818461, 0.51722877],
       [0.31370777, 0.96754046, 0.49657739, 0.20120677, 0.66716621,
        0.0821497 , 0.16378276, 0.91985771, 0.49665325, 0.8457499 ],
       [0.72751219, 0.81195663, 0.4208293 , 0.99637758, 0.7625382 ,
        0.19825064, 0.25903235, 0.34308253, 0.77192913, 0.0075951 ],
       [0.69824691, 0.5831496 , 0.82567637, 0.19304844, 0.59296457,
        0.10432653, 0.40064766, 0.86054815, 0.57487988, 0.31338111],
       [0.99592592, 0.20089943, 0.15726197, 0.9348104 , 0.39339617,
        0.99977081, 0.5891156 , 0.38910129, 0.16787758, 0.61470723],
       [0.29082873, 0.83263534, 0.91729532, 0.49260945, 0.21212094,
        0.84532711, 0.92392002, 0.40031357, 0.04143174, 0.84339664],
       [0.62150867, 0.70043703, 0.03709967, 0.13286754, 0.6641113 ,
        0.01675459, 0.96832055, 0.21466117, 0.84962639, 0.92527158],
       [0.4536019 , 0.9581899 , 0.6787377

In [33]:
p_max = np.max(p)
p_max

0.9997708149617474

In [34]:
p_min = np.min(p)
p_min

0.007595100589617876

### 6. Create a random vector of size 30 and find the mean value.

In [40]:
q = np.random.randint(100,size=(30))
print(q)
print('size : ',len(q))

[ 3 33 30 97 94  3 42 88 72 64  9 76 52  5 85 92 23 37 80 33 77 39 43 99
 66 19  2 42 52 87]
size :  30


In [41]:
q_mean = np.mean(q)
q_mean

51.46666666666667